Added Krita to open hardware
open-minds/awesome-openminds-team pull request #120
Opened 2020-10-21 16:39 UTC by Caitlin-Fotheringham

https://invent.kde.org/graphics/krita

Krita is an open-source, free design application tool, compared against Photoshop for being the best free version of similar software.

## Summary:

Added:

- one
- two
- three

2020-10-21 17:07 UTC, Fcmam5 requested changes

2020-10-21 17:07 UTC, Fcmam5 commented on README.md
> +* [Krita](https://krita.org/en/) An end-to-end solution for creating digital art files
Wrong category, please create a new design category after `Extensions for Text editors` and theb add Krita,

2020-10-22 08:07 UTC, Caitlin-Fotheringham commented
I have created the category, I noticed Extensions for Text Editors is not linked at the top in the menu, so wasn't sure whether to add design or not to the menu as well. Do you want me to add it to the menu?

2020-10-22 08:53 UTC, oussamabonnor1 commented
That would be lovely, yes. Thanks!

2020-10-22 10:29 UTC, oussamabonnor1 approved these changes
Thank you for your contribution!

2020-10-22 10:32 UTC, Fcmam5 approved these changes

2020-10-22 10:34 UTC, merged